"""
Insuretechdaily — Streamlit Job Intelligence Dashboard

Visual dashboard for reviewing AI-scored insurance, MGA, reinsurance and
insurtech job opportunities generated by the automated scanner.
"""

from __future__ import annotations

from pathlib import Path
from typing import Iterable

import pandas as pd
import streamlit as st


st.set_page_config(
    page_title="Insuretechdaily Job Intelligence",
    page_icon="💼",
    layout="wide",
)


st.markdown(
    """
    <style>
    .main-header {
        background: linear-gradient(135deg, #132238 0%, #315f8f 100%);
        padding: 1.8rem;
        border-radius: 12px;
        color: white;
        margin-bottom: 1.2rem;
    }
    .main-header h1 { color: white; margin-bottom: 0.3rem; }
    .main-header p { color: #d7e7f7; margin: 0; }
    .job-card {
        background: white;
        border: 1px solid #e5e7eb;
        border-left: 6px solid #315f8f;
        border-radius: 10px;
        padding: 1rem 1.2rem;
        margin-bottom: 0.9rem;
    }
    .score {
        float: right;
        font-size: 1.4rem;
        font-weight: 800;
        color: #132238;
    }
    .company-pill {
        display: inline-block;
        padding: 0.25rem 0.6rem;
        background: #e8f1fb;
        color: #174a7c;
        border-radius: 999px;
        font-size: 0.78rem;
        font-weight: 700;
        margin-bottom: 0.45rem;
    }
    .small-muted { color: #64748b; font-size: 0.85rem; }
    </style>
    """,
    unsafe_allow_html=True,
)


st.markdown(
    """
    <div class="main-header">
        <h1>💼 Insuretechdaily Job Intelligence Dashboard</h1>
        <p>Review AI-scored insurance operations, MGA, reinsurance and insurtech job opportunities.</p>
    </div>
    """,
    unsafe_allow_html=True,
)


SAMPLE_JOBS = [
    {
        "company": "Example MGA Platform",
        "role": "Senior Insurance Operations Manager",
        "score": 91,
        "rationale": "Strong fit: MGA operations, delegated authority, bordereaux oversight and transformation exposure.",
        "location": "Remote EU",
        "url": "https://example.com/job-1",
    },
    {
        "company": "Claims AI Insurtech",
        "role": "Insurance Transformation Consultant",
        "score": 84,
        "rationale": "Good fit: claims automation, AI workflow design and insurance operations consulting.",
        "location": "Hybrid Barcelona / Remote",
        "url": "https://example.com/job-2",
    },
    {
        "company": "Global Reinsurer",
        "role": "Reinsurance Operations Lead",
        "score": 78,
        "rationale": "Relevant reinsurance operations role with process improvement and data quality ownership.",
        "location": "Remote Europe",
        "url": "https://example.com/job-3",
    },
    {
        "company": "Generic SaaS Company",
        "role": "Customer Support Associate",
        "score": 42,
        "rationale": "Low fit: limited insurance domain relevance and insufficient seniority.",
        "location": "On-site",
        "url": "https://example.com/job-4",
    },
]


COLUMN_ALIASES = {
    "company": ["company", "company_name", "employer", "organisation", "organization"],
    "role": ["role", "title", "job_title", "position"],
    "score": ["score", "fit_score", "match_score", "relevance_score", "ai_score"],
    "rationale": ["rationale", "reason", "scoring_rationale", "match_rationale", "summary", "ai_rationale"],
    "location": ["location", "job_location", "region"],
    "url": ["url", "job_url", "link", "apply_url", "action_url"],
}


@st.cache_data
def read_csv(uploaded_file) -> pd.DataFrame:
    return pd.read_csv(uploaded_file)


def find_col(columns: Iterable[str], aliases: list[str]) -> str | None:
    normalized = {c.lower().strip().replace(" ", "_"): c for c in columns}
    for alias in aliases:
        if alias in normalized:
            return normalized[alias]
    return None


def normalize_jobs(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    output = pd.DataFrame()

    for target, aliases in COLUMN_ALIASES.items():
        source = find_col(df.columns, aliases)
        if source is not None:
            output[target] = df[source]
        else:
            output[target] = "" if target != "score" else 0

    output["score"] = pd.to_numeric(output["score"], errors="coerce").fillna(0).astype(float)
    output["company"] = output["company"].fillna("Unknown company").astype(str)
    output["role"] = output["role"].fillna("Untitled role").astype(str)
    output["rationale"] = output["rationale"].fillna("No rationale provided.").astype(str)
    output["location"] = output["location"].fillna("").astype(str)
    output["url"] = output["url"].fillna("").astype(str)

    return output


def load_latest_local_csv() -> pd.DataFrame | None:
    patterns = ["*.csv", "results/*.csv", "outputs/*.csv", "data/*.csv"]
    candidates: list[Path] = []
    for pattern in patterns:
        candidates.extend(Path(".").glob(pattern))

    candidates = [p for p in candidates if p.is_file()]
    if not candidates:
        return None

    latest = max(candidates, key=lambda p: p.stat().st_mtime)
    st.sidebar.caption(f"Loaded local file: `{latest}`")
    return pd.read_csv(latest)


def render_job_card(row: pd.Series) -> None:
    role = row.get("role", "Untitled role")
    company = row.get("company", "Unknown company")
    score = row.get("score", 0)
    rationale = row.get("rationale", "")
    location = row.get("location", "")
    url = row.get("url", "")

    role_html = f"<a href='{url}' target='_blank'>{role}</a>" if isinstance(url, str) and url.startswith("http") else role

    st.markdown(
        f"""
        <div class="job-card">
            <span class="score">{score:.0f}</span>
            <span class="company-pill">{company}</span>
            <h4>{role_html}</h4>
            <p>{rationale}</p>
            <div class="small-muted">{location}</div>
        </div>
        """,
        unsafe_allow_html=True,
    )


with st.sidebar:
    st.markdown("### 📥 Data source")
    uploaded = st.file_uploader("Upload jobs CSV", type=["csv"])
    use_sample = st.toggle("Use sample data", value=True)
    try_local = st.toggle("Try latest local CSV", value=False)

    st.markdown("---")
    st.markdown("### 🎛️ Filters")
    score_threshold = st.slider("Top match threshold", 0, 100, 75)
    search_text = st.text_input("Search company / role")


if uploaded is not None:
    raw_df = read_csv(uploaded)
elif try_local:
    local_df = load_latest_local_csv()
    raw_df = local_df if local_df is not None else pd.DataFrame(SAMPLE_JOBS)
    if local_df is None:
        st.warning("No local CSV found. Showing sample data instead.")
elif use_sample:
    raw_df = pd.DataFrame(SAMPLE_JOBS)
else:
    st.info("Upload a jobs CSV or enable sample data.")
    st.stop()

jobs = normalize_jobs(raw_df)

if search_text.strip():
    q = search_text.strip().lower()
    jobs = jobs[
        jobs["company"].str.lower().str.contains(q, na=False)
        | jobs["role"].str.lower().str.contains(q, na=False)
    ]

top_matches = jobs[jobs["score"] >= score_threshold].sort_values("score", ascending=False)
all_jobs_sorted = jobs.sort_values("score", ascending=False)

st.markdown("### KPI Overview")
col1, col2, col3, col4 = st.columns(4)
with col1:
    st.metric("Total jobs scanned", len(jobs))
with col2:
    st.metric("Top matches", len(top_matches))
with col3:
    st.metric("Average score", f"{jobs['score'].mean():.1f}" if len(jobs) else "0.0")
with col4:
    conversion = (len(top_matches) / len(jobs) * 100) if len(jobs) else 0
    st.metric("Match rate", f"{conversion:.0f}%")

st.divider()

left, right = st.columns([2, 1])

with left:
    st.markdown(f"### Top Matches — Score ≥ {score_threshold}")
    if top_matches.empty:
        st.warning("No jobs meet the selected threshold.")
    else:
        for _, row in top_matches.iterrows():
            render_job_card(row)

with right:
    st.markdown("### Score Distribution")
    if len(jobs):
        buckets = pd.cut(
            jobs["score"],
            bins=[0, 50, 75, 85, 100],
            labels=["<50", "50–74", "75–84", "85–100"],
            include_lowest=True,
        )
        score_dist = buckets.value_counts().sort_index().reset_index()
        score_dist.columns = ["score_range", "count"]
        st.bar_chart(score_dist, x="score_range", y="count")

    st.markdown("### Companies")
    company_counts = jobs["company"].value_counts().head(10).reset_index()
    company_counts.columns = ["company", "jobs"]
    st.dataframe(company_counts, use_container_width=True, hide_index=True)

st.divider()
st.markdown("### Full Jobs Table")
st.dataframe(all_jobs_sorted, use_container_width=True, hide_index=True)

st.download_button(
    "⬇ Download top matches",
    data=top_matches.to_csv(index=False).encode("utf-8"),
    file_name="top_insurance_job_matches.csv",
    mime="text/csv",
)
